config/routes.rb
Rails.application.routes.draw do
  get '404', to: 'errors#error_404', code: 404

  resources :offers

  get 'static_pages/home'

  get 'static_pages/contact'

  get 'static_pages/about'

  get 'static_pages/customer_services'

  get 'static_pages/services_for_applicants'

  get 'static_pages/reference'

  get 'login' => 'user_sessions#new'
  post 'logout' => 'user_sessions#destroy'

  resources :users
  resources :user_sessions

  root 'static_pages#home'

end

app/models/offer.rb
# == Schema Information
#
# Table name: offers
#
#  id                :integer          not null, primary key
#  external_offer_id :string
#  offerdate         :date
#  last_update       :datetime
#  position          :string
#  location          :string
#  content           :string
#  url               :string
#  company           :string
#  ico               :string
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  offer_source_id   :integer
#
# Indexes
#
#  index_offers_on_external_offer_id  (external_offer_id)
#  index_offers_on_offer_source_id    (offer_source_id)
#

class Offer < ActiveRecord::Base

  belongs_to :offer_source

  has_and_belongs_to_many :jobtypes
  has_and_belongs_to_many :offercategories
  has_and_belongs_to_many :offerpositions
  has_and_belongs_to_many :offerregions

  before_save :generate_timestamp
  before_save :set_external_offer_id
  validates :position, presence: true

  scope :by_offerdate, -> { order 'offerdate' }
  scope :by_company, -> (company) { where 'company = ?', company}

  #enum offer_source: ['local', 'profesia.sk']

  def generate_timestamp
    if self.offer_source_id == OfferSource.local.id
      self.last_update = Time.zone.now
    end
  end

  def set_external_offer_id
    if self.offer_source_id == OfferSource.profesia.id && self.external_offer_id.present? == false
      self.external_offer_id = 'not_set'
    end
  end

end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :require_login, except: [:show]
  before_action :set_offer, only: [:show, :edit, :update, :destroy]
  before_action :set_codelists, only: [:new, :edit, :create, :update]

  # GET /offers
  # GET /offers.json
  def index
    Import::Profesia.new.import!
    @offers = Offer.all
  end

  # GET /offers/1
  # GET /offers/1.json
  def show
  end

  # GET /offers/new
  def new
    @offer = Offer.new
  end

  # GET /offers/1/edit
  def edit
  end

  # POST /offers
  # POST /offers.json
  def create
    @offer = Offer.new(offer_params)
    @offer.offer_source = OfferSource.local
    respond_to do |format|
      if @offer.save
        format.html { redirect_to @offer, notice: t('offer.created') }
        format.json { render :show, status: :created, location: @offer }
      else
        format.html { render :new }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /offers/1
  # PATCH/PUT /offers/1.json
  def update
    respond_to do |format|
      if @offer.update(offer_params)
        format.html { redirect_to @offer, notice: t('offer.updated') }
        format.json { render :show, status: :ok, location: @offer }
      else
        format.html { render :edit }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offers/1
  # DELETE /offers/1.json
  def destroy
    @offer.destroy
    respond_to do |format|
      format.html { redirect_to offers_url, notice: t('offer.destroyed') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_offer
      @offer = Offer.find(params[:id])
    end

    def set_codelists
      @offercategories = Offercategory.by_name
      @jobtypes = Jobtype.by_name
      @offerregions = Offerregion.by_name
      @offerpositions = Offerposition.by_name
    end

  # Never trust parameters from the scary internet, only allow the white list through.
    def offer_params
      params.require(:offer).permit(:external_offer_id, :offerdate, :position, :location, :content, :url, :company, :ico, { :offercategory_ids => [] }, { :jobtype_ids => [] }, { :offerposition_ids => [] }, { :offerregion_ids => [] })
    end
end

app/helpers/offers_helper.rb
module OffersHelper

  def offer_url(offer)
    if offer.url.present?
      link_to offer.offer_source.name, url_with_protocol(offer.url), target: '_blank'
    else
      t('offer.not_url')
    end
  end

  def url_with_protocol(url)
    /^http/i.match(url) ? url : "http://#{url}"
  end
end

app/views/offers/_form.html.erb
<%= simple_form_for(@offer) do |f| %>
  <%= f.error_notification %>

    <%= f.input :external_offer_id %>
    <%= f.input :offerdate %>
    <%= f.input :position %>
    <%= f.input :location %>
    <%= f.input :content %>
    <%= f.input :url %>
    <%= f.input :company %>
    <%= f.input :ico %>
    <%= f.association :offercategories, collection: @offercategories, html_input: { multiple: true } %>
    <%= f.association :jobtypes, collection: @jobtypes, html_input: { multiple: true } %>
    <%= f.association :offerpositions, collection: @offerpositions, html_input: { multiple: true } %>
    <%= f.association :offerregions, collection: @offerregions, html_input: { multiple: true } %>

    <%= f.button :submit %>
<% end %>

app/views/offers/edit.html.erb
<h1>Editing Offer</h1>

<%= render 'form' %>

<br>
<%= link_to 'Show', @offer, class: 'btn btn-default' %>
<%= link_to 'Back', offers_path, class: 'btn btn-default' %>

app/views/offers/index.html.erb
<h1>Listing Offers</h1>

<table class="table table-striped">
  <thead>
  <tr>
    <th>External offer ID</th>
    <th>Offerdate</th>
    <th>Last update</th>
    <th>Position</th>
    <th>Location</th>
    <th>Url</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @offers.each do |offer| %>
      <tr>
        <td><%= t(offer.external_offer_id) if offer.external_offer_id.present? %></td>
        <td><%= l offer.offerdate %></td>
        <td><%= l offer.last_update, format: :long %></td>
        <td><%= offer.position %></td>
        <td><%= offer.location %></td>
        <td>
          <% if offer.url.present? %>
              <%= link_to offer.offer_source.name, url_with_protocol(offer.url), target: '_blank' %>
          <% end %>
        </td>
        <td><%= link_to 'Show', offer %></td>
        <td>
          <% if offer.offer_source_id == OfferSource.local.id %>
              <%= link_to 'Edit', edit_offer_path(offer) %>
          <% end %>
        </td>
        <td>
          <% if offer.offer_source_id == OfferSource.local.id %>
              <%= link_to 'Destroy', offer, method: :delete, data: {confirm: 'Are you sure?'} %>
          <% end %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Offer', new_offer_path, class: 'btn btn-default' %>

app/views/offers/new.html.erb
<h1>New Offer</h1>

<%= render 'form' %>

<br>
<%= link_to 'Back', offers_path, class: 'btn btn-default' %>

app/views/offers/show.html.erb
<p>
  <strong>External offer ID:</strong>
  <%= t(@offer.external_offer_id) if @offer.external_offer_id.present? %>
</p>

<p>
  <strong>Offerdate:</strong>
  <%= l(@offer.offerdate) %>
</p>

<p>
  <strong>Last update:</strong>
  <%= l(@offer.last_update, format: :long) %>
</p>

<p>
  <strong>Position:</strong>
  <%= @offer.position %>
</p>

<p>
  <strong>Location:</strong>
  <%= @offer.location %>
</p>

<p>
  <strong>Content:</strong>
  <%= @offer.content %>
</p>

<p>
  <strong>Url:</strong>
  <%= offer_url(@offer) %>
</p>

<p>
  <strong>Company:</strong>
  <%= @offer.company %>
</p>

<p>
  <strong>Ico:</strong>
  <%= @offer.ico %>
</p>

<% if @offer.offercategories.length > 0 %>
    <p>
      <strong>Offer categories:</strong>
      <% @offer.offercategories.each do |oc| %>
        <div><%= oc.name %></div>
    <% end %>
    </p>
<% end %>

<% if @offer.offerpositions.length > 0 %>
    <p>
      <strong>Offer positions:</strong>
      <% @offer.offerpositions.each do |op| %>
        <div><%= op.name %></div>
    <% end %>
    </p>
<% end %>

<% if @offer.offerregions.length > 0 %>
    <p>
      <strong>Offer regions:</strong>
      <% @offer.offerregions.each do |oreg| %>
        <div><%= oreg.name %></div>
    <% end %>
    </p>
<% end %>

<% if current_user && @offer.offer_source_id == OfferSource.local.id %>
    <%= link_to 'Edit', edit_offer_path(@offer), class: 'btn btn-default' %>
<% end %>
<%= link_to 'Back', :back, class: 'btn btn-default' %>